# Generated by Django 3.0.8 on 2020-09-21 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='wallet_ammount',
            new_name='wallet_amount',
        ),
    ]
