# Generated by Django 3.0.8 on 2020-09-22 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200921_1007'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favourites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('price', models.CharField(max_length=20)),
                ('img', models.URLField()),
                ('link', models.URLField()),
                ('acccount', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Account')),
            ],
        ),
    ]
