# Generated by Django 3.0.8 on 2020-09-22 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_favourites'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favourites',
            old_name='acccount',
            new_name='account',
        ),
    ]
