# Generated by Django 3.0.8 on 2020-09-22 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_requests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requests',
            name='requester',
            field=models.CharField(max_length=20),
        ),
    ]
