# Generated by Django 3.0.8 on 2020-09-22 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200922_1348'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requests',
            old_name='requester',
            new_name='requester_name',
        ),
        migrations.AddField(
            model_name='requests',
            name='requester_id',
            field=models.IntegerField(null=True),
        ),
    ]
