# Generated by Django 3.0.8 on 2020-09-22 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200922_1356'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requests',
            old_name='requester_name',
            new_name='requester_username',
        ),
    ]
