# Generated by Django 3.0.8 on 2020-09-22 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_favourites_website'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Account')),
            ],
        ),
    ]
